#!/bin/bash
  if [ $(which apt-get) == "/usr/bin/apt-get" ]; then
      echo "apt-get is good"
  else
  	alias apt-get='/usr/bin/apt-get'
  fi
  echo
  if [ $(which ufw) == "/usr/sbin/ufw" ]; then
  	echo "ufw is good"
  else
  	alias ufw='/usr/sbin/ufw'
  fi
  echo
  if [ $(which ls) == "/bin/ls" ]; then
  	echo "ls is good"
  else
  	alias ls='/bin/ls'
  fi
  echo
  if [ $(which grep) == "/bin/grep" ]; then
  	echo "grep is good"
  else
  	alias grep='/bin/grep'
  fi
  echo
  if [ $(which sudo) == "/usr/bin/sudo" ]; then
  	echo "sudo is good"
  else
  	alias sudo='/usr/bin/sudo'
  fi
  echo
  if [ $(which cp) == "/bin/cp" ]; then
  	echo "cp is good"
  else
  	alias cp='/bin/cp'
  fi
  echo
  if [ $(which mv) == "/bin/mv" ]; then
  	echo "mv is good"
  else
  	alias mv='/bin/mv'
